@host = http://localhost:5000/api/v1/simulate

POST {{ host }} 
Content-Type: application/json

{
    "TankIds": [
        "e228a0c3-6c17-4655-85e2-50450031733a", 
        "14cd09d2-776d-45d0-9e1f-abcd391a4137"
    ], 
    "MapId" : "e69ee3e3-fc31-4908-80ac-e9b0800f772c",
    "Seed": 42
}