@host = http://localhost:5000/api/v1/simulate

POST {{ host }} 
Content-Type: application/json

{
    "TankIds": [
        "0d9b997c-566b-4389-b9a2-83ec7fa9cc90", 
        "ff882f3f-ee75-4018-9ebf-d562ad2760e0"
    ], 
    "MapId" : "ff8d6cee-6c58-4433-98d5-e64c1912e9c7",
    "Seed": 42
}